name = input ("What is your name? ")
city = input ("Which city do you live in? ")
title = input ("What is your Job Title? ")
Exp = input ("How much experience you have in years? ")

print(f"======== PROFESSIONAL PROFILE ========")
print(f"NAME        :   {name.upper()}")
print(f"City        :   {city}")
print(f"Job Title   :   {title}")
print(f"Experience  :   {Exp} years")
print(f"By 2030     :   {int(Exp) + 5} years of experience")
print(f"Name length :   {len(name)} characters")